### ISSUE TITLE
console-1.0-M2-1下报错无法使用

### ISSUE THREAD

**Issue by MrTC1277** [Pai2Chen/mirai-console-addition#1]
2020-08-26 17:11:19 W/stderr: java.lang.reflect.InvocationTargetException
2020-08-26 17:11:19 W/stderr:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-26 17:11:19 W/stderr:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-26 17:11:19 W/stderr:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-26 17:11:19 W/stderr:   at java.lang.reflect.Method.invoke(Method.java:498)
2020-08-26 17:11:19 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
2020-08-26 17:11:19 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
2020-08-26 17:11:19 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
2020-08-26 17:11:19 W/stderr:   at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:55)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.internal.command.CompositeCommandInternalKt$createSubCommand$7.invokeSuspend(CompositeCommandInternal.kt:321)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.internal.command.CompositeCommandInternalKt$createSubCommand$7.invoke(CompositeCommandInternal.kt)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseAndExecute$mirai_console(CompositeCommandInternal.kt:136)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.command.SimpleCommand.onCommand(SimpleCommand.kt:48)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.command.CommandManagerImpl.executeCommandDetailed(CommandManagerImpl.kt:278)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommandDetailed(CommandManager.kt:170)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$2.invokeSuspend(ConsoleThread.kt:66)
2020-08-26 17:11:19 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-08-26 17:11:19 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
2020-08-26 17:11:19 W/stderr:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-08-26 17:11:19 W/stderr:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$service$1$1.invoke(ConsoleThread.kt:29)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$service$1$1.invoke(ConsoleThread.kt)
2020-08-26 17:11:19 W/stderr:   at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2020-08-26 17:11:19 W/stderr: Caused by: java.io.IOException: ϵͳ�Ҳ���ָ����·����
2020-08-26 17:11:19 W/stderr:   at java.io.WinNTFileSystem.createFileExclusively(Native Method)
2020-08-26 17:11:19 W/stderr:   at java.io.File.createNewFile(File.java:1012)
2020-08-26 17:11:19 W/stderr:   at net.mamoe.mirai.console.plugin.PluginFileExtensions.file(Plugin.kt:72)
2020-08-26 17:11:19 W/stderr:   at top.fan2tao.mirai.consoleaddition.AdditionBase$Config.save(AdditionBase.kt:51)
2020-08-26 17:11:19 W/stderr:   at top.fan2tao.mirai.consoleaddition.subplugins.AutoLogin$autoLoginCommand.handle(AutoLogin.kt:42)
2020-08-26 17:11:19 W/stderr:   ... 22 more

**Comment by Dreamail** [comment]
请检查你的磁盘是否有故障
尝试换到另一个物理磁盘上运行

**Comment by dfaofeng** [comment]
![image](https://user-images.githubusercontent.com/14891398/91458080-b0238b00-e8b7-11ea-8ddf-51570ea4bd4f.png)
正常使用.
